version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:9
    steps:
      - checkout:
          path: git@github.com:bpetetot/react-unlimited.git
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}

  build-lib:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - run: yarn build:lib
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}

  build-docs:
    docker:
      - image: circleci/node:9
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          - v1-dependencies-
      - run: yarn install --frozen-lockfile
      - run: yarn build:docs
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}

workflows:
  version: 2
  build:
    jobs:
      - lint
      - build-lib
      - build-docs
